/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.selManagement.Vue;


import java.awt.Color;
import java.awt.Font;
import java.time.LocalDateTime;
import java.util.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

import org.selManagement.Controller.ButtonRenderer;
import org.selManagement.Controller.CommandController;
import org.selManagement.Model.*;

import org.selManagement.Controller.ProductControler;
import org.selManagement.Model.Products;

/**
 * @author almamy
 */
public class Dashboard extends javax.swing.JFrame {

    private boolean newCategorie = true;
    ProductControler products = new ProductControler();
    CommandController command;

    int userId = 0;
    Object[] rowData;
    Object[][] objects;
    JButton update = new JButton("Update");
    /**
     * Creates new form Dashboard
     */
    public Dashboard(int userId) {
        initComponents();
        this.userId = userId;
        this.command = new CommandController(this.userId);
//        this.products = new ProductControler();
        this.products.getAllProduct();
        this.listProduct.getTableHeader().setFont(new Font("Arimo", Font.BOLD, 14));
        this.listProduct.getTableHeader().setForeground(new Color(255, 255, 255));
        this.listProduct.getTableHeader().setOpaque(false);
        this.listProduct.getTableHeader().setBackground(new Color(36, 34, 54));
//        67,58,167
        this.listProduct.setRowHeight(25);
//        this.qtField.setBackground(new Color(231,236,239));
        this.categorie.setBackground(new Color(231, 236, 239));
        this.productCombo.addItem("Maillonnaise");
        this.payementEtat.addItem("payer");
        this.statutCommand.addItem("livrer");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        topBar = new javax.swing.JPanel();
        titleBar = new javax.swing.JLabel();
        menueBtn = new javax.swing.JLabel();
        sideBar = new javax.swing.JPanel();
        dashbordBtn = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        commandBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        userBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        productBtn = new javax.swing.JPanel();
        productTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        centerContainer = new javax.swing.JPanel();
        dashboardPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userPanel = new javax.swing.JPanel();
        commandPanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        nomField = new javax.swing.JTextField();
        usernameLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        usernameLabel9 = new javax.swing.JLabel();
        usernameLabel10 = new javax.swing.JLabel();
        compagnieField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        usernameLabel11 = new javax.swing.JLabel();
        usernameLabel12 = new javax.swing.JLabel();
        usernameLabel13 = new javax.swing.JLabel();
        statutCommand = new javax.swing.JComboBox<>();
        telephoneField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        montantField = new javax.swing.JTextField();
        quantiterSpinner = new javax.swing.JSpinner();
        usernameLabel14 = new javax.swing.JLabel();
        usernameLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        usernameLabel16 = new javax.swing.JLabel();
        usernameLabel17 = new javax.swing.JLabel();
        productCombo = new javax.swing.JComboBox<>();
        payementEtat = new javax.swing.JComboBox<>();
        produitPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduct = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        nameProduct = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameLabel2 = new javax.swing.JLabel();
        prixProduct = new javax.swing.JTextField();
        usernameLabel5 = new javax.swing.JLabel();
        usernameLabel6 = new javax.swing.JLabel();
        categorie = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        quantiterProduct = new javax.swing.JSpinner();
        usernameLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        descriptionProduct = new javax.swing.JTextArea();
        newCate = new java.awt.Button();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(652, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(444, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(237, 246, 249));
        jPanel2.setLayout(new java.awt.BorderLayout());

        topBar.setBackground(new java.awt.Color(67, 58, 167));
        topBar.setAlignmentX(0.0F);
        topBar.setAlignmentY(0.0F);
        topBar.setName(""); // NOI18N

        titleBar.setFont(new java.awt.Font("Arimo", 1, 36)); // NOI18N
        titleBar.setForeground(new java.awt.Color(255, 255, 255));
        titleBar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleBar.setText("BkoSaler");

        menueBtn.setBackground(new java.awt.Color(67, 58, 167));
        menueBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menueBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menueBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        menueBtn.setMinimumSize(new java.awt.Dimension(45, 45));
        menueBtn.setOpaque(true);
        menueBtn.setPreferredSize(new java.awt.Dimension(45, 45));
        menueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menueBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
                topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topBarLayout.createSequentialGroup()
                                .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(menueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topBarLayout.setVerticalGroup(
                topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(titleBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(topBarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(menueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(topBar, java.awt.BorderLayout.NORTH);

        sideBar.setBackground(new java.awt.Color(36, 34, 54));
        sideBar.setPreferredSize(new java.awt.Dimension(232, 552));

        dashbordBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashbordBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashbordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordBtnMouseClicked(evt);
            }
        });

        dashboardBtn.setFont(new java.awt.Font("Arimo", 1, 28)); // NOI18N
        dashboardBtn.setForeground(new java.awt.Color(36, 34, 54));
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardBtn.setText("Bashboard");
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout dashbordBtnLayout = new javax.swing.GroupLayout(dashbordBtn);
        dashbordBtn.setLayout(dashbordBtnLayout);
        dashbordBtnLayout.setHorizontalGroup(
                dashbordBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashbordBtnLayout.createSequentialGroup()
                                .addContainerGap(13, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        dashbordBtnLayout.setVerticalGroup(
                dashbordBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashbordBtnLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dashboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        commandBtn.setBackground(new java.awt.Color(255, 255, 255));
        commandBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        commandBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commandBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arimo", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 34, 54));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Vente");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vente.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout commandBtnLayout = new javax.swing.GroupLayout(commandBtn);
        commandBtn.setLayout(commandBtnLayout);
        commandBtnLayout.setHorizontalGroup(
                commandBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(commandBtnLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        commandBtnLayout.setVerticalGroup(
                commandBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandBtnLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(commandBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        userBtn.setBackground(new java.awt.Color(255, 255, 255));
        userBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arimo", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 34, 54));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setOpaque(true);

        javax.swing.GroupLayout userBtnLayout = new javax.swing.GroupLayout(userBtn);
        userBtn.setLayout(userBtnLayout);
        userBtnLayout.setHorizontalGroup(
                userBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userBtnLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(16, 16, 16))
        );
        userBtnLayout.setVerticalGroup(
                userBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userBtnLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(userBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(userBtnLayout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(userBtnLayout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(9, 9, 9))))
        );

        productBtn.setBackground(new java.awt.Color(255, 255, 255));
        productBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    productBtnMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productBtnMouseEntered(evt);
            }
        });

        productTxt.setFont(new java.awt.Font("Arimo", 1, 28)); // NOI18N
        productTxt.setForeground(new java.awt.Color(36, 34, 54));
        productTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productTxt.setText("Produits");
        productTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTxtMouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/product.png"))); // NOI18N
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setOpaque(true);

        javax.swing.GroupLayout productBtnLayout = new javax.swing.GroupLayout(productBtn);
        productBtn.setLayout(productBtnLayout);
        productBtnLayout.setHorizontalGroup(
                productBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBtnLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        productBtnLayout.setVerticalGroup(
                productBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productBtnLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(productTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
                sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashbordBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commandBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarLayout.setVerticalGroup(
                sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sideBarLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(dashbordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(productBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(commandBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(291, Short.MAX_VALUE))
        );

        jPanel2.add(sideBar, java.awt.BorderLayout.WEST);

        dashboardPanel.setBackground(new java.awt.Color(237, 246, 249));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 34, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total Produits");

        jLabel4.setBackground(new java.awt.Color(229, 229, 229));
        jLabel4.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(63, 55, 201));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Produits");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 34, 54));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Command");

        jLabel6.setBackground(new java.awt.Color(229, 229, 229));
        jLabel6.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 55, 201));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 34, 54));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total Vente");

        jLabel8.setBackground(new java.awt.Color(229, 229, 229));
        jLabel8.setFont(new java.awt.Font("Arimo", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(63, 55, 201));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap(279, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))
        );
        dashboardPanelLayout.setVerticalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashboardPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(672, Short.MAX_VALUE))
        );

        userPanel.setBackground(new java.awt.Color(237, 246, 249));

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
                userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1109, Short.MAX_VALUE)
        );
        userPanelLayout.setVerticalGroup(
                userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 801, Short.MAX_VALUE)
        );

        commandPanel.setBackground(new java.awt.Color(237, 246, 249));
        commandPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commandPanelMouseClicked(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(231, 236, 239));

        nomField.setBackground(new java.awt.Color(231, 236, 239));
        nomField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        nomField.setForeground(new java.awt.Color(36, 34, 54));
        nomField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nomField.setOpaque(true);

        usernameLabel4.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel4.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel4.setText("Nom");

        emailField.setBackground(new java.awt.Color(231, 236, 239));
        emailField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(36, 34, 54));
        emailField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        emailField.setOpaque(true);

        usernameLabel9.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel9.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel9.setText("Email");

        usernameLabel10.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel10.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel10.setText("Compagnie");

        compagnieField.setBackground(new java.awt.Color(231, 236, 239));
        compagnieField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        compagnieField.setForeground(new java.awt.Color(36, 34, 54));
        compagnieField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        compagnieField.setOpaque(true);
        compagnieField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compagnieFieldActionPerformed(evt);
            }
        });

        addressField.setBackground(new java.awt.Color(231, 236, 239));
        addressField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        addressField.setForeground(new java.awt.Color(36, 34, 54));
        addressField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        addressField.setOpaque(true);

        usernameLabel11.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel11.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel11.setText("Address");

        usernameLabel12.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel12.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel12.setText("Produit");

        usernameLabel13.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel13.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel13.setText("Montant");

        statutCommand.setBackground(new java.awt.Color(231, 236, 239));
        statutCommand.setForeground(new java.awt.Color(36, 34, 54));
        statutCommand.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        statutCommand.setPreferredSize(new java.awt.Dimension(64, 24));
        statutCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutCommandActionPerformed(evt);
            }
        });

        telephoneField.setBackground(new java.awt.Color(231, 236, 239));
        telephoneField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        telephoneField.setForeground(new java.awt.Color(36, 34, 54));
        telephoneField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        telephoneField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telephoneField.setOpaque(true);

        jButton3.setText("Enregistrer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton3ActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButton4.setText("Annuler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        montantField.setEditable(false);
        montantField.setBackground(new java.awt.Color(231, 236, 239));
        montantField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        montantField.setForeground(new java.awt.Color(36, 34, 54));
        montantField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        montantField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        montantField.setOpaque(true);

        quantiterSpinner.setModel(new javax.swing.SpinnerNumberModel());
        quantiterSpinner.setToolTipText("");
        quantiterSpinner.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        quantiterSpinner.setOpaque(true);

        usernameLabel14.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel14.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel14.setText("Telephone");

        usernameLabel15.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel15.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel15.setText("Quantiter");

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setForeground(new java.awt.Color(36, 34, 54));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null},
                },
                new String[]{
                        "Num Command", "Poduit", "Quantiter", "Montant", "Compagnie", "Telephone", "Address", ""
                }
        ) {
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setGridColor(new java.awt.Color(204, 204, 204));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(67, 58, 167));
        jTable2.setShowGrid(false);
        jTable2.setShowHorizontalLines(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(6).setHeaderValue("Address");
        }

        usernameLabel16.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel16.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel16.setText("Etat Payement ");

        usernameLabel17.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel17.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel17.setText("Status disponibliter");

        productCombo.setBackground(new java.awt.Color(231, 236, 239));
        productCombo.setForeground(new java.awt.Color(36, 34, 54));
        productCombo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        productCombo.setPreferredSize(new java.awt.Dimension(64, 24));
        productCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboActionPerformed(evt);
            }
        });

        payementEtat.setBackground(new java.awt.Color(231, 236, 239));
        payementEtat.setForeground(new java.awt.Color(36, 34, 54));
        payementEtat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        payementEtat.setPreferredSize(new java.awt.Dimension(64, 24));
        payementEtat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payementEtatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(payementEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(109, 109, 109)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(180, 180, 180)
                                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(statutCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(usernameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(usernameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(usernameLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(109, 109, 109)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(usernameLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(usernameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(compagnieField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(usernameLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(109, 109, 109)
                                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(usernameLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(usernameLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(productCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(109, 109, 109)
                                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(montantField)
                                                                        .addComponent(quantiterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(usernameLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(usernameLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel12)
                                        .addComponent(usernameLabel10)
                                        .addComponent(usernameLabel4)
                                        .addComponent(usernameLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(compagnieField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(quantiterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(productCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usernameLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(usernameLabel11)
                                                .addComponent(usernameLabel14)
                                                .addComponent(usernameLabel13)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(montantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(usernameLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(statutCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(payementEtat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
                commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1115, Short.MAX_VALUE)
                        .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        commandPanelLayout.setVerticalGroup(
                commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 896, Short.MAX_VALUE)
                        .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        produitPane.setBackground(new java.awt.Color(237, 246, 249));
        produitPane.setLayout(new java.awt.BorderLayout());

        listProduct.setBackground(new java.awt.Color(255, 255, 255));
        listProduct.setForeground(new java.awt.Color(36, 34, 54));
        for (Products product : this.products.getAllProduct()) {

            listProduct.setModel(new javax.swing.table.DefaultTableModel(
                    new Object[][]{
                            new Object[]{product.getCodeProduct(), product.getNomPoduct(), product.getCategorieProduct(), product.getDescription(), String.valueOf(product.getQuantiter()), String.valueOf(product.getPrixUnit()),  new JButton("Modifier"), new JButton("Suprimer")},
                    },
                    new String[]{
                            "Num Produit", "Poduit", "Categorie", "Description", "Quantiter", "prix", "Modifier", "Suprimer"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                        false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
        }
        listProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listProduct.setGridColor(new java.awt.Color(204, 204, 204));
        listProduct.setRowHeight(25);
        listProduct.setSelectionBackground(new java.awt.Color(67, 58, 167));
        listProduct.setShowGrid(false);
        listProduct.setShowHorizontalLines(true);
        listProduct.getTableHeader().setReorderingAllowed(false);
        ButtonRenderer buttonRenderer = new ButtonRenderer();
        listProduct.getColumnModel().getColumn(6).setCellRenderer(buttonRenderer);
        listProduct.getColumnModel().getColumn(7).setCellRenderer(buttonRenderer);
        jScrollPane1.setViewportView(listProduct);

        produitPane.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 400));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(231, 236, 239));

        nameProduct.setBackground(new java.awt.Color(231, 236, 239));
        nameProduct.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        nameProduct.setForeground(new java.awt.Color(36, 34, 54));
        nameProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nameProduct.setOpaque(true);

        usernameLabel.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel.setText("Produit");

        usernameLabel2.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel2.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel2.setText("Prix");

        prixProduct.setBackground(new java.awt.Color(231, 236, 239));
        prixProduct.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        prixProduct.setForeground(new java.awt.Color(36, 34, 54));
        prixProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        prixProduct.setOpaque(true);
        prixProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prixProductActionPerformed(evt);
            }
        });

        usernameLabel5.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel5.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel5.setText("Categorie");

        usernameLabel6.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel6.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel6.setText("Description");

        categorie.setBackground(new java.awt.Color(231, 236, 239));
        categorie.setForeground(new java.awt.Color(36, 34, 54));
        categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        categorie.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        categorie.setPreferredSize(new java.awt.Dimension(64, 24));

        saveBtn.setBackground(new java.awt.Color(36, 34, 54));
        saveBtn.setFont(new java.awt.Font("Arimo", 1, 15)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Enregistrer");
        saveBtn.setBorderPainted(false);
        saveBtn.setOpaque(true);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(36, 34, 54));
        cancelBtn.setFont(new java.awt.Font("Arimo", 1, 15)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Annuler");
        cancelBtn.setOpaque(true);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        quantiterProduct.setModel(new javax.swing.SpinnerNumberModel());
        quantiterProduct.setToolTipText("");
        quantiterProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        quantiterProduct.setOpaque(true);

        usernameLabel8.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel8.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel8.setText("Quantiter");

        descriptionProduct.setBackground(new java.awt.Color(255, 255, 255));
        descriptionProduct.setColumns(20);
        descriptionProduct.setRows(5);
        descriptionProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        descriptionProduct.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(descriptionProduct);

        newCate.setActionCommand("newCategorie");
        newCate.setBackground(new java.awt.Color(36, 34, 54));
        newCate.setFont(new java.awt.Font("Arimo", 1, 12)); // NOI18N
        newCate.setForeground(new java.awt.Color(255, 255, 255));
        newCate.setLabel("New Categorie");
        newCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(usernameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(109, 109, 109)
                                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(usernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(prixProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(109, 109, 109)
                                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(usernameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(109, 109, 109)
                                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(quantiterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(usernameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jScrollPane3)))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(377, 377, 377)
                                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(83, 83, 83)
                                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(61, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(newCate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(newCate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel5)
                                        .addComponent(usernameLabel2)
                                        .addComponent(usernameLabel)
                                        .addComponent(usernameLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(prixProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(nameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(categorie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(quantiterProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addComponent(usernameLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
        );

        newCate.getAccessibleContext().setAccessibleName("newCategorie");

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        produitPane.add(jPanel6, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout centerContainerLayout = new javax.swing.GroupLayout(centerContainer);
        centerContainer.setLayout(centerContainerLayout);
        centerContainerLayout.setHorizontalGroup(
                centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(produitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerContainerLayout.createSequentialGroup()
                                        .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );
        centerContainerLayout.setVerticalGroup(
                centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(produitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE))
                        .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(commandPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(centerContainerLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap()))
        );

        jPanel2.add(centerContainer, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x = 232;
    boolean isToggled = true;

    private void menueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueBtnMouseClicked
        System.out.println(this.sideBar.getSize());
        isToggled = !isToggled;
        if (isToggled) {
            // Action lorsque le bouton est activé (toggle ON)
//                    x =57;
            if (x == 57) {
                System.out.println("Bouton activé (toggle ON) " + x + "/" + isToggled);
                this.sideBar.setSize(232, this.sideBar.getSize().height);
                this.dashbordBtn.setSize(232, this.dashbordBtn.getSize().height);
                x = 232;
            }
        } else {
            // Action lorsque le bouton est désactivé (toggle OFF)
            if (x == 232) {
                System.out.println("Bouton désactivé (toggle OFF) " + x + "/" + isToggled);
                this.sideBar.setSize(57, this.sideBar.getSize().height);
                this.dashbordBtn.setSize(57, this.dashbordBtn.getSize().height);
                x = 57;
            }
        }
    }//GEN-LAST:event_menueBtnMouseClicked

    private void dashbordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordBtnMouseClicked
        // TODO add your handling code here:
        this.userPanel.setVisible(false);
        this.produitPane.setVisible(false);
        this.dashboardPanel.setVisible(true);
        this.commandPanel.setVisible(false);

    }//GEN-LAST:event_dashbordBtnMouseClicked

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        // TODO add your handling code here:
        this.userPanel.setVisible(false);
        this.produitPane.setVisible(false);
        this.dashboardPanel.setVisible(true);
        this.commandPanel.setVisible(false);
        this.categorie.removeAllItems();

        for (Object category : this.products.Categoriefunc()) {
            System.out.println("=======" + category.toString());
            this.categorie.addItem(category.toString());
        }
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here: 
        this.userPanel.setVisible(false);
        this.dashboardPanel.setVisible(false);
        this.produitPane.setVisible(false);
        this.commandPanel.setVisible(true);
        this.categorie.removeAllItems();

        for (Object category : this.products.Categoriefunc()) {
            System.out.println("=======" + category.toString());
            this.categorie.addItem(category.toString());
        }


    }//GEN-LAST:event_jLabel2MouseClicked

    private void commandBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commandBtnMouseClicked
        // TODO add your handling code here:
        this.userPanel.setVisible(false);
        this.dashboardPanel.setVisible(false);
        this.produitPane.setVisible(false);
        this.commandPanel.setVisible(true);
        this.categorie.removeAllItems();
//        this.productCombo.addItem("test001");
        for (Object category : this.products.Categoriefunc()) {
            System.out.println("=======" + category.toString());
            this.categorie.addItem(category.toString());
        }


    }//GEN-LAST:event_commandBtnMouseClicked

    private void userBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBtnMouseClicked
        // TODO add your handling code here:
        this.produitPane.setVisible(false);
        this.dashboardPanel.setVisible(false);
        this.commandPanel.setVisible(false);
        this.userPanel.setVisible(true);
    }//GEN-LAST:event_userBtnMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.produitPane.setVisible(false);
        this.commandPanel.setVisible(false);
        this.dashboardPanel.setVisible(false);
        this.userPanel.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void prixProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prixProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prixProductActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        String prod = this.products.createProduct(this.nameProduct.getText(), (String) this.categorie.getSelectedItem(), this.descriptionProduct.getText(), Double.parseDouble(this.prixProduct.getText()), Integer.parseInt(this.quantiterProduct.getValue().toString()));
        switch (prod) {
            case "success":
                JOptionPane.showMessageDialog(rootPane, "Insertion avec success");

                break;
            case "exist":
                JOptionPane.showMessageDialog(rootPane, "Cet produit exist deja");

                break;
            case "error":
                JOptionPane.showMessageDialog(rootPane, "Veuiller renseingner correctement les information sur le produit");
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Une Erreur c'est produite");
                throw new AssertionError();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void productTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTxtMouseClicked
        // TODO add your handling code here:

        this.produitPane.setVisible(true);
        this.dashboardPanel.setVisible(false);
        this.userPanel.setVisible(false);
        this.commandPanel.setVisible(false);
//        DefaultTableModel model = (DefaultTableModel) this.listProduct.getModel();
//        for (Products product : this.products.getAllProduct()) {
//            Object[] rowData = {product.getCodeProduct(), product.getNomPoduct(), product.getCategorieProduct(), product.getDescription(), product.getQuantiter(), product.getPrixUnit()};
//
//            model.addRow(rowData);
//        }
    }//GEN-LAST:event_productTxtMouseClicked

    private void productBtnMouseClicked(java.awt.event.MouseEvent evt) throws SQLException {
        // TODO add your handling code here: 
        this.produitPane.setVisible(true);
        this.dashboardPanel.setVisible(false);
        this.userPanel.setVisible(false);
        this.commandPanel.setVisible(false);
        this.listProduct.removeAll();
//        DefaultTableModel model = (DefaultTableModel) this.listProduct.getModel();
//        for (Products product : this.products.getAllProduct()) {
//            Object[] rowData = {product.getCodeProduct(), product.getNomPoduct(), product.getCategorieProduct(), product.getDescription(), product.getQuantiter(), product.getPrixUnit(), new JButton("Update"), new JButton("Delete")};
////            System.out.println(this.products.getAllProduct().size());
//            model.addRow(rowData);
//        }

    }

    private void commandPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commandPanelMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_commandPanelMouseClicked

    private void productBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_productBtnMouseEntered

    private void compagnieFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compagnieFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_compagnieFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        CommandController command = new CommandController();
        this.command.createCommand(this.nomField.getText(), this.compagnieField.getText(), (String) this.productCombo.getSelectedItem(), (int) this.quantiterSpinner.getValue(), this.emailField.getText(), this.addressField.getText(), this.telephoneField.getText(), this.montantField.getText(), (String) this.payementEtat.getSelectedItem(), (String) this.statutCommand.getSelectedItem());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void newCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCateActionPerformed
        // TODO add your handling code here:
        JTextField new_categorie = new JTextField();
        JRadioButton etatCategorie = new JRadioButton("Etat");

        etatCategorie.setSelected(true);
        etatCategorie.setSize(35, 35);
        Object[] message = {"Categorie:", new_categorie, "", etatCategorie,};
        int createCategorie = JOptionPane.showConfirmDialog(rootPane, message, "Formulaire", JOptionPane.OK_CANCEL_OPTION);
        System.out.println("Soumit!!!!=> " + createCategorie + " === " + JOptionPane.OK_CANCEL_OPTION);

        if (createCategorie != JOptionPane.OK_CANCEL_OPTION) {
            if (!new_categorie.getText().equals("")) {
                System.out.println(new_categorie.getText());
                if (etatCategorie.isSelected()) {
                    this.newCategorie = true;
                } else {
                    this.newCategorie = false;
                }

                this.products.newCategorieFunc(new_categorie.getText(), this.newCategorie);
                this.categorie.addItem(new_categorie.getText());
//                if (cat) {
//                    JOptionPane.showMessageDialog(rootPane, "Categorie creer avec succe");
//                } else {
//                    JOptionPane.showMessageDialog(rootPane, "Categorie non creer");
//
//                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Champs mal renseigner");

            }
        }


    }//GEN-LAST:event_newCateActionPerformed

    private void statutCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutCommandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statutCommandActionPerformed

    private void productComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboActionPerformed

    private void payementEtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payementEtatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payementEtatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard(this.).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> categorie;
    private javax.swing.JPanel centerContainer;
    private javax.swing.JPanel commandBtn;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JTextField compagnieField;
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JPanel dashbordBtn;
    private javax.swing.JTextArea descriptionProduct;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable listProduct;
    private javax.swing.JLabel menueBtn;
    private javax.swing.JTextField montantField;
    private javax.swing.JTextField nameProduct;
    private java.awt.Button newCate;
    private javax.swing.JTextField nomField;
    private javax.swing.JComboBox<String> payementEtat;
    private javax.swing.JTextField prixProduct;
    private javax.swing.JPanel productBtn;
    private javax.swing.JComboBox<String> productCombo;
    private javax.swing.JLabel productTxt;
    private javax.swing.JPanel produitPane;
    private javax.swing.JSpinner quantiterProduct;
    private javax.swing.JSpinner quantiterSpinner;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel sideBar;
    private javax.swing.JComboBox<String> statutCommand;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JLabel titleBar;
    private javax.swing.JPanel topBar;
    private javax.swing.JPanel userBtn;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel10;
    private javax.swing.JLabel usernameLabel11;
    private javax.swing.JLabel usernameLabel12;
    private javax.swing.JLabel usernameLabel13;
    private javax.swing.JLabel usernameLabel14;
    private javax.swing.JLabel usernameLabel15;
    private javax.swing.JLabel usernameLabel16;
    private javax.swing.JLabel usernameLabel17;
    private javax.swing.JLabel usernameLabel2;
    private javax.swing.JLabel usernameLabel4;
    private javax.swing.JLabel usernameLabel5;
    private javax.swing.JLabel usernameLabel6;
    private javax.swing.JLabel usernameLabel8;
    private javax.swing.JLabel usernameLabel9;
    // End of variables declaration//GEN-END:variables

}
