/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.selManagement.Vue;

/**
 *
 * @author almamy
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBar = new javax.swing.JPanel();
        dashbordBtn = new javax.swing.JPanel();
        dashbordBtn1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menueBtn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        centerContainer = new javax.swing.JPanel();
        pane1 = new javax.swing.JPanel();
        usernameField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        usernameField2 = new javax.swing.JTextField();
        usernameLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        usernameLabel8 = new javax.swing.JLabel();
        usernameLabel6 = new javax.swing.JLabel();
        usernameField7 = new javax.swing.JTextField();
        usernameField6 = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        usernameLabel7 = new javax.swing.JLabel();
        usernameField1 = new javax.swing.JTextField();
        usernameLabel1 = new javax.swing.JLabel();
        usernameLabel5 = new javax.swing.JLabel();
        pane2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 34, 54));
        jPanel1.setPreferredSize(new java.awt.Dimension(232, 552));

        sideBar.setBackground(new java.awt.Color(36, 34, 54));
        sideBar.setAlignmentX(0.0F);
        sideBar.setAlignmentY(0.0F);
        sideBar.setAutoscrolls(true);
        sideBar.setFocusable(false);
        sideBar.setName(""); // NOI18N
        sideBar.setRequestFocusEnabled(false);
        sideBar.setLayout(new java.awt.BorderLayout());

        dashbordBtn.setBackground(new java.awt.Color(255, 255, 255));
        dashbordBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashbordBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout dashbordBtnLayout = new javax.swing.GroupLayout(dashbordBtn);
        dashbordBtn.setLayout(dashbordBtnLayout);
        dashbordBtnLayout.setHorizontalGroup(
            dashbordBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dashbordBtnLayout.setVerticalGroup(
            dashbordBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        dashbordBtn1.setBackground(new java.awt.Color(255, 255, 255));
        dashbordBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashbordBtn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashbordBtn1Layout = new javax.swing.GroupLayout(dashbordBtn1);
        dashbordBtn1.setLayout(dashbordBtn1Layout);
        dashbordBtn1Layout.setHorizontalGroup(
            dashbordBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dashbordBtn1Layout.setVerticalGroup(
            dashbordBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dashbordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashbordBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(dashbordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(dashbordBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel6.setBackground(new java.awt.Color(67, 58, 167));
        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 75));

        jLabel3.setFont(new java.awt.Font("Arimo", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BkoSaler");

        menueBtn.setBackground(new java.awt.Color(67, 58, 167));
        menueBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menueBtn.setIcon(new javax.swing.ImageIcon("/home/almamy/Documents/Progrmming/Project/SelManagement/src/main/resources/images/pngegg (4).png")); // NOI18N
        menueBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menueBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        menueBtn.setMinimumSize(new java.awt.Dimension(45, 45));
        menueBtn.setOpaque(true);
        menueBtn.setPreferredSize(new java.awt.Dimension(45, 45));
        menueBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menueBtnMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1678, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(menueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.NORTH);

        centerContainer.setAlignmentX(0.0F);
        centerContainer.setAlignmentY(0.0F);
        centerContainer.setMinimumSize(new java.awt.Dimension(790, 552));
        centerContainer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                centerContainerMouseClicked(evt);
            }
        });

        pane1.setBackground(new java.awt.Color(102, 204, 255));

        usernameField3.setBackground(new java.awt.Color(231, 236, 239));
        usernameField3.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        usernameField3.setForeground(new java.awt.Color(36, 34, 54));
        usernameField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField3.setOpaque(true);

        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        usernameField2.setBackground(new java.awt.Color(231, 236, 239));
        usernameField2.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        usernameField2.setForeground(new java.awt.Color(36, 34, 54));
        usernameField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField2.setOpaque(true);
        usernameField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameField2ActionPerformed(evt);
            }
        });

        usernameLabel2.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel2.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel2.setText("Compagnie");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel());
        jSpinner1.setToolTipText("");
        jSpinner1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jSpinner1.setOpaque(true);

        usernameLabel8.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel8.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel8.setText("Produit");

        usernameLabel6.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel6.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel6.setText("Montant");

        usernameField7.setEditable(false);
        usernameField7.setBackground(new java.awt.Color(231, 236, 239));
        usernameField7.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        usernameField7.setForeground(new java.awt.Color(36, 34, 54));
        usernameField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameField7.setOpaque(true);

        usernameField6.setBackground(new java.awt.Color(231, 236, 239));
        usernameField6.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        usernameField6.setForeground(new java.awt.Color(36, 34, 54));
        usernameField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameField6.setOpaque(true);

        usernameField.setBackground(new java.awt.Color(231, 236, 239));
        usernameField.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        usernameField.setForeground(new java.awt.Color(36, 34, 54));
        usernameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField.setOpaque(true);

        usernameLabel.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel.setText("Nom");

        usernameLabel3.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel3.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel3.setText("Address");

        jComboBox1.setBackground(new java.awt.Color(231, 236, 239));
        jComboBox1.setForeground(new java.awt.Color(36, 34, 54));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jComboBox1.setPreferredSize(new java.awt.Dimension(64, 24));

        usernameLabel7.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel7.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel7.setText("Telephone");

        usernameField1.setBackground(new java.awt.Color(231, 236, 239));
        usernameField1.setFont(new java.awt.Font("Arimo", 0, 18)); // NOI18N
        usernameField1.setForeground(new java.awt.Color(36, 34, 54));
        usernameField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameField1.setOpaque(true);

        usernameLabel1.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel1.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel1.setText("Email");

        usernameLabel5.setFont(new java.awt.Font("Arimo", 1, 14)); // NOI18N
        usernameLabel5.setForeground(new java.awt.Color(36, 34, 54));
        usernameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usernameLabel5.setText("Produit");

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane1Layout.createSequentialGroup()
                .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameField6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109)
                        .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField7, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jSpinner1)
                            .addComponent(usernameLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(430, Short.MAX_VALUE))
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel5)
                    .addComponent(usernameLabel2)
                    .addComponent(usernameLabel)
                    .addComponent(usernameLabel8))
                .addGap(18, 18, 18)
                .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameLabel7)
                        .addComponent(usernameLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usernameField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(usernameField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(usernameField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(110, 110, 110)
                .addGroup(pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        pane2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1458, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout centerContainerLayout = new javax.swing.GroupLayout(centerContainer);
        centerContainer.setLayout(centerContainerLayout);
        centerContainerLayout.setHorizontalGroup(
            centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerContainerLayout.setVerticalGroup(
            centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(centerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerContainerLayout.createSequentialGroup()
                    .addComponent(pane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(centerContainer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int x = 232;
    boolean isToggled = true;
    private void menueBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menueBtnMouseClicked
        System.out.println(this.jPanel1.getSize());
        isToggled = !isToggled;
                if (isToggled) {
                    // Action lorsque le bouton est activé (toggle ON)
//                    x =57;
                    if (x == 57) {
                    System.out.println("Bouton activé (toggle ON) "+x+"/"+isToggled);
                        this.jPanel1.setSize(232, this.jPanel1.getSize().height);
                        x=232;
                    }
                } else {
                    // Action lorsque le bouton est désactivé (toggle OFF)
                    if (x == 232) {
                    System.out.println("Bouton désactivé (toggle OFF) "+x+"/"+isToggled);
                        this.jPanel1.setSize(57, this.jPanel1.getSize().height);
                        x = 57;
                    }
                }
    }//GEN-LAST:event_menueBtnMouseClicked

    private void centerContainerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_centerContainerMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_centerContainerMouseClicked

    private void dashbordBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordBtnMouseClicked
        // TODO add your handling code here:
        this.pane1.setVisible(false);
        this.pane2.setVisible(true);
    }//GEN-LAST:event_dashbordBtnMouseClicked

    private void dashbordBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordBtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dashbordBtn1MouseClicked

    private void dashbordBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashbordBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dashbordBtnMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerContainer;
    private javax.swing.JPanel dashbordBtn;
    private javax.swing.JPanel dashbordBtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel menueBtn;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    private javax.swing.JPanel sideBar;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField usernameField1;
    private javax.swing.JTextField usernameField2;
    private javax.swing.JTextField usernameField3;
    private javax.swing.JTextField usernameField6;
    private javax.swing.JTextField usernameField7;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    private javax.swing.JLabel usernameLabel2;
    private javax.swing.JLabel usernameLabel3;
    private javax.swing.JLabel usernameLabel5;
    private javax.swing.JLabel usernameLabel6;
    private javax.swing.JLabel usernameLabel7;
    private javax.swing.JLabel usernameLabel8;
    // End of variables declaration//GEN-END:variables
}
